// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID          int32
	Originalurl string
	Hash        string
	CreatedAt   pgtype.Int8
	Owner       pgtype.Int8
}

type User struct {
	ID   int32
	Name pgtype.Text
}
